spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fxtrading}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:fxuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:fxpassword}

spring.jpa.hibernate.ddl-auto=update
